Change Vantaa nature area URL
City-of-Helsinki/servicemap-ui pull request #1159
Opened 2024-06-10 08:00 UTC by japauliina

Change the Vantaa nature area URL as the previous URL did not always work as expected.

[Refs](https://trello.com/c/hys2Z5Zj/1561-vantaan-luonnonsuojelualueiden-n%C3%A4yt%C3%A4-alueen-tiedot-linkit-ohjautuu-v%C3%A4%C3%A4rin)

_Note to developers: remember to update your .env file._

2024-06-10 08:09 UTC, mhieta approved these changes
Looks good! 👍

2024-06-10 09:07 UTC, mhieta requested changes
@japauliina Looks like browser tests failed and therefore still need some fixing.

2024-06-10 09:35 UTC, japauliina commented
> @japauliina Looks like browser tests failed and therefore still need some fixing.

Failing test had no do with this change and re-running the jobs fixed it. Need to study more why.

2024-06-11 07:12 UTC, mhieta approved these changes

2024-06-11 07:12 UTC, merged