Fix JavaScript issues and warnings
City-of-Helsinki/servicemap-ui pull request #1192
Opened 2024-10-18 14:25 UTC by mhieta

Fix various JavaScript issues and warnings.

Details:
- Upgrade React Helmet to v6
  - This will remedy deprecated React component lifecycle warnings
- Set default values for unit names
  - ReadFeedbackLink requires fi/sv/en unit names, thus introduce defaults for them
- Change nested link-tag to division
  - This fixes warning: `validateDOMNesting(...): <a> cannot appear as a descendant of <a>`
- Render DescriptionText SSR and CSR the same way
  - This fixes warning: `validateDOMNesting(...): <div> cannot appear as a descendant of <div>`
- Disable reservations fetching for now
  - Reservations API is outdated, thus disable this integration for now

2024-10-23 07:34 UTC, jorilindell commented on server/dataFetcher.js
> +    // reservationsFetch({ unit: `tprek:${id}` }, null, reservationFetchEnd, fetchOnError, null, null, controller)
What is the reason why this data fetching is commented out? Maybe there could be comment to tell the reason for future developers or just removing the line if it's not needed.

2024-10-23 07:34 UTC, jorilindell commented on src/utils/unitHelper.js
> +    return unit;
This could be changed to:
```
const { name = {} } = unit;

return {
  ...unit,
  name: {
    ...name,
    fi: name.fi || '',
    sv: name.sv || '',
    en: name.en || '',
   },
};
```
- The default value for name ensures that if unit.name is undefined, it initializes it as an empty object
- This approach maintains immutability and avoids side effects by returning a new object with updated values

You can also simplify this further by adding default value for unit. In this way you can avoid existence check.
```
const setDefaults = (unit = {}) => {
    const { name = {} } = unit;

    return {
        ...unit,
        name: {
           ...name,
            fi: name.fi || '',
            sv: name.sv || '',
            en: name.en || ''
        }
    };
};
```

2024-10-23 13:30 UTC, mhieta commented on server/dataFetcher.js
> +    // reservationsFetch({ unit: `tprek:${id}` }, null, reservationFetchEnd, fetchOnError, null, null, controller)
Reason for this was that this particular Reservations API is completely outdated and is not even online anymore. But yes, I'll remove this whole line for now, until we get a new integration for this.

2024-10-25 04:17 UTC, mhieta commented on src/utils/unitHelper.js
> +    return unit;
Good points, updated this now.

2024-10-28 07:32 UTC, japauliina requested changes
Nice work with the commits! It was easy to follow the changes.

Left some minor comments in the code. Also waiting for the tests to pass before accepting.

To commit 'Change defaultProps to JS default parameters' I would wish for a short explanation about why the change was made.

Overall nice work!

2024-10-28 10:14 UTC, mhieta commented on src/index.css
> +}
Updated.

2024-10-28 10:14 UTC, mhieta commented on browserTests/views/unitPageTest.js
> +});
Updated.

2024-10-28 10:16 UTC, mhieta commented
> To commit 'Change defaultProps to JS default parameters' I would wish for a short explanation about why the change was made.

Updated commit with more detailed explanation.

2024-10-30 07:50 UTC, japauliina approved these changes

2024-10-30 07:52 UTC, merged