Download tool + memoized selector refactor
City-of-Helsinki/servicemap-ui pull request #461
Opened 2020-09-03 12:28 UTC by mikkoisa

- Refactor reselect selectors to work correctly by removing state passing: previously state was given as parameter to selector, this causes memoization to not work.
- Update react-redux to get new redux hook useSelector, that is used in download tool hook.
- Add download tool hook

**Note**: new redux hooks allows easier access to state on functional components. These can be used to replace the connect HOC and mapStateToProps.

2020-09-03 12:31 UTC, mikkoisa commented
Still todo: add download tool to tool menu when it's available

2020-09-08 11:54 UTC, Dremars reviewed
This works way better than the previous implementation. Good job!

2020-09-08 11:54 UTC, Dremars commented on src/views/AddressView/utils/fetchAddressUnits.js
> +    include: '',
What's this meant to do?

2020-09-08 11:54 UTC, Dremars commented on src/utils/orderUnits.js
> +      });
I'm wondering if this could be moved near fetching so it's not run each time order is change but rather when data is first time fetched. 

In the future I think we might need to have some kind of handler to process each data type (unit, address, etc.) before inserting it to redux.

2020-09-08 12:32 UTC, mikkoisa commented on src/views/AddressView/utils/fetchAddressUnits.js
> +    include: '',
Used to override default include value, this was not supposed to be included in the commit. Will remove.

2020-09-09 08:42 UTC, mikkoisa commented on src/utils/orderUnits.js
> +      });
Good point. However shortcoming counting requires user settings, which can change after the fetch, so this needs to be recalculated each time user settings or unit data changes.

2020-09-10 07:06 UTC, Dremars commented on src/utils/orderUnits.js
> +      });
Good point

2020-09-10 07:51 UTC, Dremars requested changes
Seems like marker rendering fails when selecting unit from search and returning back to search page. Units are not updated.

2020-09-10 09:09 UTC, Dremars approved these changes

2020-09-10 10:01 UTC, merged