Feature/printing
City-of-Helsinki/servicemap-ui pull request #501
Opened 2020-10-14 12:22 UTC by Dremars

New printing tool for ToolMenu. Printing tool opens separate view on top of the current one with correct map state for printing purposes.

Updated Leaflet library

2020-10-16 11:19 UTC, Dremars commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) Tulostaminen](https://trello.com/c/YUTFfS0v/68-3-tulostaminen)

2020-10-16 11:19 UTC, Dremars commented
Need to add translations before merging

2020-10-22 08:52 UTC, mikkoisa requested changes

2020-10-22 08:52 UTC, mikkoisa commented on src/views/PrintView/PrintView.js
> +                                <Typography variant="subtitle1">
The unit name seems to be h6, which is confusing for screen readers. These could be all h1 or we could add a single main title h1 to the top of the page ("Printing view" for example) and these would be h2.

2020-10-22 09:24 UTC, Dremars commented on src/views/PrintView/PrintView.js
> +                                <Typography variant="subtitle1">
Those were meant to be paragraphs. It seems variant="subtitle1" change component to `h6`. Changing component to `p`

2020-10-22 14:12 UTC, mikkoisa approved these changes

2020-10-28 08:28 UTC, merged