Feature/service tree units fetch
City-of-Helsinki/servicemap-ui pull request #521
Opened 2020-11-16 09:42 UTC by mikkoisa

2020-11-17 10:40 UTC, Dremars requested changes
Spent some time to go through the code and it looks really good. Some minor improvements for clarity might be needed.

For accessibility I noticed that Loading texts when opening accordion element and when loading units are not read for NVDA. Also when unit loading is done there is no verbal indication that loading has completed. But the actual loading progress sound is working correctly which helps.

2020-11-17 10:40 UTC, Dremars commented on src/views/ServiceTreeView/ServiceTreeView.js
> +  };
Wasn't this same code in serviceTree selector as well. Can we export that?

2020-11-17 10:40 UTC, Dremars commented on src/views/ServiceTreeView/ServiceTreeView.js
> +  };
I'm wondering if this kind of redux logic should be in redux folder or as a seperate  utility file specific to ServiceTreeView. This component seems to have a lot of logic within.

2020-11-18 08:43 UTC, mikkoisa commented on src/views/ServiceTreeView/ServiceTreeView.js
> +  };
Yes, it seems that this fetch does not actually interact directly with the component anymore, all fetch result data is passed through redux to the component. I'll move it to redux.

2020-11-18 08:44 UTC, mikkoisa commented on src/views/ServiceTreeView/ServiceTreeView.js
> +  };
Good call, will change.

2020-11-23 14:24 UTC, mikkoisa commented
Need to figure out how to handle selecting checkbox with screenreader. Loading units to map is useless to screenreader users.

2021-10-20 06:15 UTC, closed without merging