Add new screen reader texts for AddressSearchBar when cleared and extra info
City-of-Helsinki/servicemap-ui pull request #548
Opened 2020-12-17 11:48 UTC by Dremars

2020-12-17 11:49 UTC, Dremars commented
- Missing translations.
- Need to investigate focus problem with newer devices. Problem persist on Android v7 even with manual focus back to input. Need to check newer Androids and iPhone

2020-12-18 07:24 UTC, mikkoisa requested changes

2020-12-18 07:24 UTC, mikkoisa commented on src/components/AddressSearchBar/AddressSearchBar.js
> +          )
For some reason React displays "0" here if no address results. Works with:
` addressResults.length
            ? (
              <FormattedMessage id="address.search.suggestion" />
            ) : null`

2020-12-18 07:36 UTC, Dremars commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) Kotiosoite-kentän korjaukset](https://trello.com/c/3fJ4BfEq/740-3-kotiosoite-kent%C3%A4n-korjaukset)

2020-12-18 07:40 UTC, Dremars commented on src/components/AddressSearchBar/AddressSearchBar.js
> +          )
Should be fixed now (bef2efa)

2020-12-18 07:42 UTC, Dremars commented
@mikkoisa Usability is still horrible on Android v7 but it seems to be inherent issue with that version. Can you check if all works fine on iPhone. I'll check Android v10 when I get a chance.

2020-12-21 15:32 UTC, Dremars commented
Seems to work pretty well on Android v10

2020-12-22 06:39 UTC, mikkoisa approved these changes
Works on iOS as well

2020-12-22 07:13 UTC, Dremars commented
Translations still missing.

2021-01-07 09:39 UTC, merged