Fix/settings focus on save
City-of-Helsinki/servicemap-ui pull request #553
Opened 2020-12-23 12:38 UTC by Dremars

- Fix settings focus breaking on save with Android. Now focus is set manually to close button.
- Fix broken cancel current changes action not resetting settings to previously saved state.

2020-12-23 16:13 UTC, Dremars commented
Works nicely on Android v7 and v10.
- Still missing tests for focus functionality

2020-12-23 16:14 UTC, Dremars commented
![](https://github.trello.services/images/mini-trello-icon.png) [(1) Asetusten tallentamisessa katoaa fokus mobiililla](https://trello.com/c/ugClHPCQ/737-1-asetusten-tallentamisessa-katoaa-fokus-mobiililla)

2021-01-04 11:33 UTC, mikkoisa requested changes
Works well on iPhone and Mac VoiceOver. However cancel button seems to have lost its border, not sure what could cause this.

<img width="437" alt="Näyttökuva 2021-1-4 kello 13 31 48" src="https://user-images.githubusercontent.com/24544230/103531135-6401dc00-4e91-11eb-97ef-413e80136177.png">

2021-01-12 07:20 UTC, mikkoisa approved these changes

2021-01-12 08:10 UTC, merged