Set accessibility result order by default
City-of-Helsinki/servicemap-ui pull request #582
Opened 2021-01-29 06:39 UTC by mikkoisa

- Use accessibility order by default if any accessibility settings are selected.

2021-01-29 06:47 UTC, mikkoisa commented
Not sure about the override importance. In these changes accessibility settings will override result orderer initialOrder prop. However, changing home address on address search bar will override accessibility ordering.

2021-01-29 12:52 UTC, Dremars requested changes

2021-01-29 12:52 UTC, Dremars commented on src/components/ResultOrderer/ResultOrderer.js
> +  ].filter(i => (i !== false && i !== null)).length;
I think we should move this to settings utility class as static function hasAccessibilitySettings or accessibilitySettingsActive etc.

2021-01-29 13:45 UTC, Dremars commented
I think override order should be adress -> accessibility -> most relevant. Accessibility is setting which user selects for general use but address which is set by user for specific action or view.

2021-02-03 08:24 UTC, mikkoisa commented on src/components/ResultOrderer/ResultOrderer.js
> +  ].filter(i => (i !== false && i !== null)).length;
Implemented this on latest commits

2021-02-03 12:08 UTC, Dremars approved these changes

2021-02-04 09:58 UTC, merged