New ErrorBoundary component
City-of-Helsinki/servicemap-ui pull request #595
Opened 2021-02-11 09:50 UTC by Dremars

New ErrorBoundary component for handling error rendering.

2021-02-11 09:52 UTC, Dremars commented
Need to change:
- Figure out correct default message and get translations
- Default error styles

2021-04-20 13:07 UTC, Dremars commented
![](https://github.trello.services/images/mini-trello-icon.png) [(2) Virheviestisivu](https://trello.com/c/7z1pzNF5/838-2-virheviestisivu)

2021-05-05 06:36 UTC, mikkoisa requested changes

2021-05-05 06:36 UTC, mikkoisa commented on src/utils/user.js
> +export default UserHelper;
I think hooks can't / shouldn't be used in classes. This class can be replaced with:
```
import { useSelector } from 'react-redux'
 
export const useTheme = () => useSelector(state => state.user.theme);
export const useLocale = () => useSelector(state => state.user.locale);
```

2021-05-05 06:36 UTC, mikkoisa commented on src/utils/user.js
> +export default UserHelper;
Otherwise looks and works really well!

2021-05-10 09:28 UTC, mikkoisa commented on src/utils/user.js
> +export default UserHelper;
Ok, that makes sense! I was using the hooks plugin for eslint and it showed errors on that, however since it works I'm not sure if it should be error.

2021-05-10 09:28 UTC, mikkoisa approved these changes

2021-05-10 09:50 UTC, merged