Use redux unit data when returning to address view
City-of-Helsinki/servicemap-ui pull request #618
Opened 2021-03-09 06:58 UTC by mikkoisa

2021-03-09 08:02 UTC, Dremars requested changes
Seems good. There doesn't seem to be much realted to redux? Was redux already used?

2021-03-10 11:57 UTC, mikkoisa commented
@Dremars The address units were already on redux. The view didn't use them and instead always fetched new units.

2021-03-12 08:05 UTC, Dremars commented on src/views/AddressView/AddressView.js
> +      if ((!a && !b) || a === b) {
I see. That makes sense

2021-03-12 08:05 UTC, Dremars approved these changes

2021-03-17 08:22 UTC, merged