Top bar settings button roles
City-of-Helsinki/servicemap-ui pull request #654
Opened 2021-04-29 09:38 UTC by mikkoisa

- Changed role aria-pressed to aria-haspopup
- Added jest tests

2021-04-30 06:27 UTC, Dremars requested changes

2021-04-30 06:27 UTC, Dremars commented on src/components/TopBar/SettingsButton/__tests__/SettingsButton.test.js
> +    mount = createMount({ wrappingComponent: Providers });
I think we could use shallow rendering in this test case. It makes snapshot way shorter and I think it allows seeing roles without problem. Mount is usually needed if component does some logic on mount or I think click events etc require mount as well. But this seems like it could work with shallow

2021-04-30 07:05 UTC, mikkoisa commented on src/components/TopBar/SettingsButton/__tests__/SettingsButton.test.js
> +    mount = createMount({ wrappingComponent: Providers });
Good point! Lets change it

2021-05-10 10:10 UTC, Dremars approved these changes

2021-05-10 10:26 UTC, merged