Fix/map button focus
City-of-Helsinki/servicemap-ui pull request #673
Opened 2021-05-17 09:12 UTC by mikkoisa

- Move zoom buttons to PanControls compoent
- Make UserLocation button aria-hidden. Update button margin adjusting
- Add default outline to links

2021-05-18 09:19 UTC, Dremars requested changes

2021-05-18 09:19 UTC, Dremars commented on browserTests/addressTest.js
> +test.only('AddressView map renders correctly', async (t) => {
I guess this .only was for testing purposes? Should be removed

2021-05-18 09:19 UTC, Dremars commented on browserTests/browserTest.js
> +test.only('Transit marker visible after zoom', async (t) => {
I guess this .only was for testing purposes? Should be removed

2021-05-19 05:52 UTC, mikkoisa commented on browserTests/addressTest.js
> +test.only('AddressView map renders correctly', async (t) => {
Good catch! Will remove

2021-05-19 07:31 UTC, Dremars approved these changes
Looks good and this is working amazingly right now! Really like the keyboard usability

2021-05-19 09:38 UTC, merged