Fix/embedded nature popup
City-of-Helsinki/servicemap-ui pull request #695
Opened 2021-06-15 11:08 UTC by mikkoisa

- Fix embedded nature area view missing popup
- Ad  left side map focus border to views without sidebar

2021-06-15 11:27 UTC, mhieta requested changes
Please check/fix constant naming, otherwise good 👍

2021-06-15 11:27 UTC, mhieta commented on src/views/MapView/MapView.js
> +    if (embeded) return;
Should this constrant be `embedded ` ?

2021-06-15 12:51 UTC, mikkoisa commented on src/views/MapView/MapView.js
> +    if (embeded) return;
True, will change those!

2021-06-16 06:12 UTC, mhieta approved these changes
Good 👍

2021-06-16 06:12 UTC, merged