Feature/area view unit progress bar
City-of-Helsinki/servicemap-ui pull request #734
Opened 2021-09-20 06:22 UTC by mikkoisa

Area view geographical unit fetch didn't have proper progress bar, which was not helpful for users.
- Added progress update option to concurrent search and
- Updated area view unit fetch redux structure to allow progress fetch

2021-09-20 08:23 UTC, Dremars requested changes

2021-09-20 08:23 UTC, Dremars commented on src/utils/newFetch/HTTPClient.js
> +  getConcurrent = async (endpoint, options, progressCallback) => {
I wanted to avoid this kind of props drilling. Can we use current onNext functionality for this progressCallback? Possibly rename it to onProgressUpdate if onNext is too specific to next functionality in sequential fetching.

2021-09-20 10:11 UTC, mikkoisa commented on src/utils/newFetch/HTTPClient.js
> +  getConcurrent = async (endpoint, options, progressCallback) => {
Okay 👍 I was trying to be as careful as possible with this. OnNext wasn't working with concurrent search, so I will create onProgressUpdate to handle these.

2021-09-21 08:12 UTC, mikkoisa commented on src/utils/newFetch/HTTPClient.js
> +  getConcurrent = async (endpoint, options, progressCallback) => {
I renamed onNext to onProgressUpdate and used it here as you suggested, seems to work well!

2021-09-22 07:39 UTC, Dremars approved these changes

2021-09-22 07:49 UTC, merged