New embedder tool
City-of-Helsinki/servicemap-ui pull request #815
Opened 2022-05-17 05:15 UTC by mikkoisa

New updated visual look for the embedder tool.

2022-05-20 09:34 UTC, Dremars requested changes
Code seems mostly fine. I'll write extra comments related to visual issues

2022-05-20 09:34 UTC, Dremars commented on src/components/TopBar/TopBar.js
> +            {simpleElement // SimpleElement prop removes top bar buttons
Maybe this could be named hideButtons etc. to be more descriptive of what actually happens. Simple element doesn't tell exactly what this prop does

2022-05-20 09:47 UTC, Dremars commented
![image](https://user-images.githubusercontent.com/7398207/169500065-cc8acd19-5a24-4314-b0a0-0dd9035170bb.png)
These scroll bars are making this quite hectic looking. Maybe those bottom scroll bars could be removed.

Also I found it confusing especially on right column that there is a big separation from the elements and vertical scrollbar. Maybe the padding could be reduced so the scrollable content is closer to the bar. This would improve association that the content is scrollable. 

It's also slightly confusing that the show list of units buttons are checkboxes on same level since both cannot be true at the same time. I feel those should be radio buttons left, bottom with extra none option by default

2022-06-01 09:43 UTC, mikkoisa commented on src/components/TopBar/TopBar.js
> +            {simpleElement // SimpleElement prop removes top bar buttons
Fixed!

2022-06-02 12:16 UTC, Dremars requested changes
Seems like hide unit list radio option doesn't work if you've first selected to show lists and then press don't show.
![image](https://user-images.githubusercontent.com/7398207/171626810-899091cf-df85-436b-a807-4a4d3a849172.png)

Also do we want to show the option for showing list when there is less than 2 units shown? For example unit page or showing specific address etc?

2022-06-06 10:28 UTC, Dremars approved these changes
Looks OK

2022-06-06 10:58 UTC, merged