Update/home browser tests
City-of-Helsinki/servicemap-ui pull request #849
Opened 2022-08-08 11:55 UTC by Dremars

Wait for #845 to be merged and move getLocation to utility before merge

2022-08-08 13:57 UTC, Dremars commented
Wait for #845 to be merged and move getLocation to utility before merge

2022-08-15 09:43 UTC, mikkoisa commented on browserTests/views/homeTest.js
> +test.only('PaperButtons work correctly', async (t) => {
Forgot only-parameter here

2022-08-15 09:46 UTC, mikkoisa requested changes
See comment. Tests look good

2022-08-15 10:12 UTC, Dremars commented on browserTests/views/homeTest.js
> +test.only('PaperButtons work correctly', async (t) => {
Fixed in 3ed9f3a

2022-08-15 10:14 UTC, mikkoisa approved these changes

2022-08-15 10:15 UTC, merged