Filter unit events by event status
City-of-Helsinki/servicemap-ui pull request #933
Opened 2023-02-15 10:47 UTC by vitalis0itu

https://trello.com/c/jThQaOCg
Filtteri menee nyt kohtuu yleiseen paikkaan. Että vaikutukset eivät rajoitu pelkästään keskusteluissa ja kortissa viitattuun paikkaan.

2023-02-15 10:49 UTC, mhieta approved these changes
LGTM 👍

2023-02-15 11:57 UTC, mhieta commented
@vitalis0itu Actually those browser tests are still failing, can you fix those?

2023-02-15 11:58 UTC, mhieta requested changes
Browser tests needs to be fixed still

2023-02-23 11:12 UTC, vitalis0itu commented
Laitetaan pois tämä PR häiritsemästä kun ei tiedetä vielä ratkaisua.

2023-02-23 11:12 UTC, closed without merging